version: "3.7"

services:
  vscode:
    image: qmcgaw/reactdevcontainer
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
    ports:
      - 3000/tcp
  storybook:
    image: qmu1/storybook-react
    volumes:
      - ..:/workspace
    command: yarn storybook
    ports:
      - 9009:9009
